from __future__ import annotations

import json
from typing import List, Set

from . import ast
from .ir import IRFunction, IRInstr, IRModule


TYPE_MAP = {
    "I8": "int8_t", "U8": "uint8_t", "I16": "int16_t", "U16": "uint16_t",
    "I32": "int32_t", "U32": "uint32_t", "I64": "int64_t", "U64": "uint64_t",
    "F64": "double", "Bool": "bool", "U0": "void",
}


class CodeGen:
    """Legacy AST codegen kept for --no-ir fallback."""

    def __init__(self):
        self.indent = 0
        self.lines: List[str] = []
        self.class_names: Set[str] = set()
        self.union_names: Set[str] = set()

    def emit(self, line: str = "") -> None:
        self.lines.append(("  " * self.indent + line) if line else "")

    def generate(self, program: ast.Program) -> str:
        from .lower import Lowerer
        from .optimize import Optimizer
        module = Lowerer().lower(program, 0)
        return IRCodeGen().generate(module)


class IRCodeGen:
    def __init__(self):
        self.indent = 0
        self.lines: List[str] = []

    def emit(self, line: str = "") -> None:
        self.lines.append(("  " * self.indent + line) if line else "")

    def generate(self, module: IRModule) -> str:
        self.lines = []
        self.emit("/* Generated by HolyC advanced compiler */")
        self.emit(f"/* source: {module.source_file} | -O{module.opt_level} */")
        self.emit("#include <stdio.h>")
        self.emit("#include <stdint.h>")
        self.emit("#include <stdbool.h>")
        self.emit("#include <stddef.h>")
        self.emit("#include <string.h>")
        self.emit("")

        for s in module.structs:
            kw = "union" if s.is_union else "struct"
            self.emit(f"typedef {kw} {s.name} {{")
            self.indent += 1
            for fname, ftype in s.fields:
                self.emit(f"{ftype} {fname};")
            self.indent -= 1
            self.emit(f"}} {s.name};")
            self.emit("")

        for g in module.globals:
            line = f"{g.type_name} {g.name}"
            if g.init:
                line += f" = {g.init}"
            self.emit(line + ";")
        if module.globals:
            self.emit("")

        has_main = any(f.name == "Main" for f in module.functions)
        for fn in module.functions:
            self._gen_function(fn)

        if has_main:
            self.emit("int main(void) {")
            self.indent += 1
            self.emit("return (int)Main();")
            self.indent -= 1
            self.emit("}")
            self.emit("")

        return "\n".join(self.lines)

    def _gen_function(self, fn: IRFunction) -> None:
        params = ", ".join(f"{t} {n}" for n, t in fn.params)
        self.emit(f"{fn.return_type} {fn.name}({params}) {{")
        self.indent += 1
        for name, typ in fn.locals.items():
            if name not in {p[0] for p in fn.params}:
                self.emit(f"{typ} {name};")
        temps = sorted({
            ins.dest for blk in fn.blocks for ins in blk.instrs
            if ins.dest and ins.dest.startswith("__t")
        })
        for t in temps:
            self.emit(f"int64_t {t};")
        for blk in fn.blocks:
            self.emit(f"{blk.name}:")
            self.indent += 1
            for ins in blk.instrs:
                self._gen_instr(ins, fn.return_type)
            self.indent -= 1
        self.indent -= 1
        self.emit("}")
        self.emit("")

    def _gen_instr(self, ins: IRInstr, ret_type: str) -> None:
        if ins.op == "assign":
            self.emit(f"{ins.dest} = {ins.args[0]};")
        elif ins.op == "binop":
            if len(ins.args) == 3 and ins.args[1] == "[]":
                self.emit(f"{ins.dest} = {ins.args[0]}[{ins.args[2]}];")
            elif len(ins.args) == 3 and ins.args[1] in (".", "->"):
                self.emit(f"{ins.dest} = {ins.args[0]}{ins.args[1]}{ins.args[2]};")
            elif len(ins.args) == 4 and ins.args[1] == "?:":
                self.emit(f"{ins.dest} = ({ins.args[0]} ? {ins.args[2]} : {ins.args[3]});")
            else:
                self.emit(f"{ins.dest} = ({ins.args[0]} {ins.args[1]} {ins.args[2]});")
        elif ins.op == "unary":
            if ins.args[0] == "++pre":
                self.emit(f"{ins.dest} = ++{ins.args[1]};")
            elif ins.args[0] == "--pre":
                self.emit(f"{ins.dest} = --{ins.args[1]};")
            elif ins.args[0] == "++post":
                self.emit(f"{ins.dest} = {ins.args[1]}++;")
            elif ins.args[0] == "--post":
                self.emit(f"{ins.dest} = {ins.args[1]}--;")
            else:
                self.emit(f"{ins.dest} = {ins.args[0]}{ins.args[1]};")
        elif ins.op == "call":
            callee, *args = ins.args
            self.emit(f"{ins.dest} = {callee}({', '.join(args)});")
        elif ins.op == "print":
            self._gen_print(ins.args)
        elif ins.op == "expr":
            self.emit(f"{ins.args[0]};")
        elif ins.op == "br":
            self.emit(f"if ({ins.args[0]}) goto {ins.label};")
        elif ins.op == "jmp":
            self.emit(f"goto {ins.label};")
        elif ins.op == "ret":
            if ins.args and ret_type != "void":
                self.emit(f"return {ins.args[0]};")
            else:
                self.emit("return;")
        elif ins.op == "asm":
            code = json.loads(ins.args[0])
            for line in code.splitlines():
                self.emit(f'__asm__ volatile("{line}");')

    def _gen_print(self, args: List[str]) -> None:
        if not args:
            return
        if args[0].startswith('"') and "%" in args[0]:
            if len(args) > 1:
                casted = []
                for a in args[1:]:
                    casted.append(a if a.startswith('"') else f"(long long)({a})")
                self.emit(f"printf({args[0]}, {', '.join(casted)});")
            else:
                self.emit(f'printf("%s", {args[0]});')
            return
        if len(args) == 1:
            self.emit(f'printf("%s", {args[0]});')
            return
        parts, cargs = [], []
        for a in args:
            if a.startswith('"'):
                parts.append("%s")
            elif "." in a and a[0].isdigit():
                parts.append("%g")
            else:
                parts.append("%lld")
            cargs.append(a if a.startswith('"') else f"(long long)({a})")
        self.emit(f'printf("{"".join(parts)}", {", ".join(cargs)});')